import { test, expect } from '@playwright/test';
import { LoginPage } from '../../src/ui/pages/login.page';
import { SidebarComponent } from '../../src/ui/components/sidebar.component';
import { automationData } from '../../src/utils/test-data.factory';
import { brandAllure } from '../../src/utils/allure';

test.describe('@ui @e2e @critical Create delivery records', () => {
  test.beforeEach(async ({ page }) => { const login = new LoginPage(page); await login.open(); await login.login(); });
  test('creates an RTM with editable generated cases', async ({ page }) => { await brandAllure('E2E RTM Creation', 'critical'); const data = automationData(); await new SidebarComponent(page).open('RTM'); await page.getByRole('button', { name: 'Create RTM', exact: true }).click(); await page.getByPlaceholder('e.g. Flash Fiber Migration').fill(data.testCaseTitle); await page.getByRole('button', { name: 'Create editable RTM', exact: true }).click(); await expect(page.getByRole('heading', { name: data.testCaseTitle })).toBeVisible(); await expect(page.getByRole('button', { name: 'Add test case', exact: true })).toBeVisible(); });
  test('creates a standalone defect from the issue board', async ({ page }) => { await brandAllure('E2E Defect Creation', 'critical'); const data = automationData(); await new SidebarComponent(page).open('Defects'); await page.getByRole('button', { name: 'New defect', exact: true }).click(); await page.locator('input[name="title"]').fill(data.testCaseTitle); await page.locator('input[name="owner"]').fill(data.owner); await page.locator('textarea[name="description"]').fill(data.objective); await page.getByRole('button', { name: 'Save defect', exact: true }).click(); await expect(page.getByRole('button', { name: /Manage issue/ })).toBeVisible(); });
  test('creates a linked test case with Smoke coverage', async ({ page }) => { await brandAllure('E2E Test Case Creation', 'critical'); const data = automationData(); await new SidebarComponent(page).open('Test management'); await page.getByRole('button', { name: 'New test case', exact: true }).click(); await page.locator('input[name="title"]').fill(data.testCaseTitle); await page.locator('input[name="module"]').fill(data.module); await page.locator('input[name="owner"]').fill(data.owner); await page.locator('textarea[name="steps"]').fill('Open the module\nValidate the expected state'); await page.locator('textarea[name="expected"]').fill('The expected state is visible.'); await page.locator('select[name="stage"]').selectOption('Smoke'); await page.getByRole('button', { name: 'Save test case', exact: true }).click(); await expect(page.getByRole('button', { name: /Manage test/ })).toBeVisible(); });
});
