'use client';

import { useEffect, useRef, useState } from 'react';
import { Camera, ChevronDown, Pencil, Plus, Search, Trash2, X } from 'lucide-react';
import './global-workspace-picker.css';
import './header-workspace-size.css';
import './workspace-sidebar-placement.css';
import './workspace-header-placement.css';
import './workspace-picker-fix.css';
import './workspace-list-alignment.css';
import './workspace-dropdown-light.css';

type Workspace = { id: string; name: string; description: string; owner?: string; startDate?: string; image?: string };
const fallback: Workspace = { id: 'ptcl-qa', name: 'PTCL QA Workspace', description: 'Default local workspace' };
const read = (): Workspace[] => { try { const saved = JSON.parse(localStorage.getItem('pf360-workspaces') ?? 'null'); return Array.isArray(saved) && saved.length ? saved : [fallback]; } catch { return [fallback]; } };

export function GlobalWorkspacePicker() {
  const [items, setItems] = useState<Workspace[]>([]), [active, setActive] = useState(''), [open, setOpen] = useState(false), [search, setSearch] = useState(''), [editing, setEditing] = useState<Workspace | null>(null), [editingImage, setEditingImage] = useState(''), [notice, setNotice] = useState(''), [creating, setCreating] = useState(false), [createImage, setCreateImage] = useState('');
  const imageInput = useRef<HTMLInputElement>(null), createImageInput = useRef<HTMLInputElement>(null), picker = useRef<HTMLDivElement>(null);
  function reload() { const next = read(); const stored = localStorage.getItem('pf360-active-workspace'); const selected = next.some(item => item.id === stored) ? stored! : next[0].id; setItems(next); setActive(selected); localStorage.setItem('pf360-workspaces', JSON.stringify(next)); localStorage.setItem('pf360-active-workspace', selected); }
  useEffect(() => { reload(); const update = () => reload(); const openEditor = (event: Event) => { const space = read().find(item => item.id === (event as CustomEvent<string>).detail); if (space) edit(space); }; window.addEventListener('pf360-workspace-changed', update); window.addEventListener('pf360-edit-workspace', openEditor); return () => { window.removeEventListener('pf360-workspace-changed', update); window.removeEventListener('pf360-edit-workspace', openEditor); }; }, []);
  useEffect(() => { const close = (event: MouseEvent) => { if (!picker.current?.contains(event.target as Node)) setOpen(false); }; const escape = (event: KeyboardEvent) => { if (event.key === 'Escape') { setOpen(false); setCreating(false); } }; document.addEventListener('mousedown', close); window.addEventListener('keydown', escape); return () => { document.removeEventListener('mousedown', close); window.removeEventListener('keydown', escape); }; }, []);
  const current = items.find(item => item.id === active) ?? fallback;
  const matches = items.filter(item => `${item.name} ${item.description} ${item.owner ?? ''}`.toLowerCase().includes(search.toLowerCase()));
  function commit(next: Workspace[], message: string) { const selected = next.some(item => item.id === active) ? active : next[0]?.id ?? ''; localStorage.setItem('pf360-workspaces', JSON.stringify(next)); localStorage.setItem('pf360-active-workspace', selected); setItems(next); setActive(selected); setNotice(message); window.dispatchEvent(new Event('pf360-workspace-changed')); }
  function choose(id: string) { localStorage.setItem('pf360-active-workspace', id); setActive(id); setOpen(false); setSearch(''); window.dispatchEvent(new Event('pf360-workspace-changed')); window.dispatchEvent(new Event('pf360-workspace-opened')); }
  function edit(space: Workspace) { setEditing(space); setEditingImage(space.image ?? ''); }
  function remove(space: Workspace) { if (items.length === 1) { setNotice('Keep at least one workspace. Create another before deleting this one.'); return; } if (window.confirm(`Delete workspace “${space.name}”? Its local workspace metadata will be removed.`)) commit(items.filter(item => item.id !== space.id), `${space.name} deleted.`); }
  function chooseImage(file?: File) { if (!file) return; if (!file.type.startsWith('image/') || file.size > 2 * 1024 * 1024) { setNotice('Choose a PNG, JPG or WebP image up to 2 MB.'); return; } const reader = new FileReader(); reader.onload = () => setEditingImage(typeof reader.result === 'string' ? reader.result : ''); reader.readAsDataURL(file); }
  function chooseCreateImage(file?: File) { if (!file) return; if (!file.type.startsWith('image/') || file.size > 2 * 1024 * 1024) { setNotice('Choose a PNG, JPG or WebP image up to 2 MB.'); return; } const reader = new FileReader(); reader.onload = () => setCreateImage(typeof reader.result === 'string' ? reader.result : ''); reader.readAsDataURL(file); }
  function create(event: React.FormEvent<HTMLFormElement>) { event.preventDefault(); const form = new FormData(event.currentTarget); const name = String(form.get('name') ?? '').trim(), description = String(form.get('description') ?? '').trim(), owner = String(form.get('owner') ?? '').trim(), startDate = String(form.get('startDate') ?? ''); if (!name || !owner || !startDate) { setNotice('Workspace name, owner and start date are required.'); return; } if (items.some(item => item.name.toLowerCase() === name.toLowerCase())) { setNotice('A workspace with this name already exists.'); return; } const created: Workspace = {id: crypto.randomUUID(), name, description, owner, startDate, image: createImage || undefined}; const next = [...items, created]; localStorage.setItem('pf360-workspaces', JSON.stringify(next)); localStorage.setItem('pf360-active-workspace', created.id); setItems(next); setActive(created.id); setCreating(false); setCreateImage(''); setNotice('Workspace created successfully.'); window.dispatchEvent(new Event('pf360-workspace-changed')); window.dispatchEvent(new Event('pf360-workspace-opened')); }
  function save(event: React.FormEvent<HTMLFormElement>) { event.preventDefault(); if (!editing) return; const form = new FormData(event.currentTarget); const name = String(form.get('name') ?? '').trim(); if (!name) { setNotice('Workspace name is required.'); return; } const updated = { ...editing, name, image: editingImage || undefined, owner: String(form.get('owner') ?? '').trim(), startDate: String(form.get('startDate') ?? ''), description: String(form.get('description') ?? '').trim() }; commit(items.map(item => item.id === updated.id ? updated : item), `${name} updated.`); setEditing(null); setEditingImage(''); }
  return <div ref={picker} className="global-workspace-picker">
    <button className="global-workspace-trigger" type="button" onClick={() => setOpen(value => !value)} aria-expanded={open}>{current.image ? <img src={current.image} alt="" /> : <span>{current.name[0] ?? 'P'}</span>}<div><small>PTCL WORKSPACE</small><strong>{current.name}</strong></div><ChevronDown size={15} /></button>
    {open && <div className="global-workspace-menu"><label className="search"><Search size={15} /><input autoFocus value={search} onChange={event => setSearch(event.target.value)} placeholder="Search workspaces…" /></label><div className="global-workspace-list">{matches.map(space => <article key={space.id} className={space.id === active ? 'active' : ''}><button type="button" className="workspace-select" onClick={() => choose(space.id)}>{space.image ? <img src={space.image} alt="" /> : <span>{space.name[0]}</span>}<div><strong>{space.name}</strong><small>{space.owner ?? space.description}</small></div></button><div className="workspace-list-actions"><button type="button" title="Edit workspace" aria-label={`Edit ${space.name}`} onClick={() => edit(space)}><Pencil size={14} /></button><button type="button" title="Delete workspace" aria-label={`Delete ${space.name}`} onClick={() => remove(space)}><Trash2 size={14} /></button></div></article>)}{!matches.length && <p>No workspace found.</p>}</div>{notice && <p className="workspace-notice">{notice}</p>}<button type="button" className="global-workspace-new" onClick={() => { setOpen(false); setCreating(true); }}><Plus size={16} />New workspace</button></div>}
    {creating && <div className="workspace-edit-overlay" onClick={() => { setCreating(false); setCreateImage(''); }}><form className="workspace-edit-panel workspace-create-panel" onSubmit={create} onClick={event => event.stopPropagation()}><div className="section-title"><div><span className="eyebrow">WORKSPACE</span><h2>Create new workspace</h2></div><button type="button" className="icon-button" aria-label="Close create workspace" onClick={() => { setCreating(false); setCreateImage(''); }}><X size={18} /></button></div><div className="workspace-image-editor"><button type="button" className="workspace-image-edit-button" onClick={() => createImageInput.current?.click()}>{createImage ? <img src={createImage} alt="Workspace preview" /> : <Camera size={20} />}</button><div><strong>Workspace image / logo</strong><small>Optional · PNG, JPG or WebP · 2 MB max</small>{createImage && <button type="button" className="text-button" onClick={() => setCreateImage('')}>Remove image</button>}</div><input ref={createImageInput} className="sr-only" type="file" accept="image/png,image/jpeg,image/webp" onChange={event => chooseCreateImage(event.target.files?.[0])} /></div><label>Workspace name *<input name="name" required autoFocus maxLength={100} placeholder="Enter workspace name" /></label><label>Workspace owner *<input name="owner" required maxLength={80} placeholder="Enter workspace owner" /></label><label>Start date *<input name="startDate" type="date" required defaultValue={new Date().toISOString().slice(0,10)} /></label><label>Description<textarea name="description" rows={3} maxLength={500} placeholder="Enter description" /></label><div className="modal-actions workspace-edit-actions"><button className="text-button" type="button" onClick={() => { setCreating(false); setCreateImage(''); }}>Cancel</button><button className="primary" type="submit">Create workspace</button></div></form></div>}
    {editing && <div className="workspace-edit-overlay" onClick={() => setEditing(null)}><form className="workspace-edit-panel" onSubmit={save} onClick={event => event.stopPropagation()}><div className="section-title"><div><span className="eyebrow">WORKSPACE SETTINGS</span><h2>Edit workspace</h2></div><button type="button" className="icon-button" onClick={() => setEditing(null)}><X size={18} /></button></div><div className="workspace-image-editor"><button type="button" className="workspace-image-edit-button" onClick={() => imageInput.current?.click()}>{editingImage ? <img src={editingImage} alt="Workspace preview" /> : <Camera size={20} />}</button><div><strong>Workspace image / logo</strong><small>Optional · PNG, JPG or WebP · 2 MB max</small>{editingImage && <button type="button" className="text-button" onClick={() => setEditingImage('')}>Remove image</button>}</div><input ref={imageInput} className="sr-only" type="file" accept="image/png,image/jpeg,image/webp" onChange={event => chooseImage(event.target.files?.[0])} /></div><label>Workspace name<input name="name" required defaultValue={editing.name} /></label><label>Owner<input name="owner" defaultValue={editing.owner} /></label><label>Start date<input name="startDate" type="date" defaultValue={editing.startDate} /></label><label>Description<textarea name="description" rows={3} defaultValue={editing.description} /></label><div className="modal-actions workspace-edit-actions"><button className="primary" type="submit">Update workspace</button><button className="text-button" type="button" onClick={() => setEditing(null)}>Cancel</button></div></form></div>}
  </div>;
}
