'use client';

import { useEffect, useState } from 'react';
import { ChevronDown, Pencil, Plus, Search, Trash2, X } from 'lucide-react';
import './global-workspace-picker.css';
import './header-workspace-size.css';
import './workspace-sidebar-placement.css';
import './workspace-header-placement.css';

type Workspace = { id: string; name: string; description: string; owner?: string; startDate?: string; image?: string };
const fallback: Workspace = { id: 'ptcl-qa', name: 'PTCL QA Workspace', description: 'Default local workspace' };
function read(): Workspace[] { try { const saved = JSON.parse(localStorage.getItem('pf360-workspaces') ?? 'null'); return Array.isArray(saved) && saved.length ? saved : [fallback]; } catch { return [fallback]; } }

export function GlobalWorkspacePicker() {
 const [items,setItems]=useState<Workspace[]>([]),[active,setActive]=useState(''),[open,setOpen]=useState(false),[search,setSearch]=useState(''),[editing,setEditing]=useState<Workspace|null>(null),[notice,setNotice]=useState('');
 function reload(){const next=read();setItems(next);const stored=localStorage.getItem('pf360-active-workspace');const selected=next.some(item=>item.id===stored)?stored!:next[0].id;localStorage.setItem('pf360-workspaces',JSON.stringify(next));localStorage.setItem('pf360-active-workspace',selected);setActive(selected)}
 useEffect(()=>{reload();const update=()=>reload();window.addEventListener('pf360-workspace-changed',update);return()=>window.removeEventListener('pf360-workspace-changed',update)},[]);
 const current=items.find(item=>item.id===active)??fallback;const matches=items.filter(item=>`${item.name} ${item.description} ${item.owner??''}`.toLowerCase().includes(search.toLowerCase()));
 function commit(next:Workspace[],message:string){localStorage.setItem('pf360-workspaces',JSON.stringify(next));setItems(next);const selected=next.some(item=>item.id===active)?active:next[0]?.id??'';localStorage.setItem('pf360-active-workspace',selected);setActive(selected);setNotice(message);window.dispatchEvent(new Event('pf360-workspace-changed'))}
 function choose(id:string){localStorage.setItem('pf360-active-workspace',id);setActive(id);setOpen(false);setSearch('');window.dispatchEvent(new Event('pf360-workspace-changed'));window.dispatchEvent(new Event('pf360-workspace-opened'))}
 function remove(space:Workspace){if(items.length===1){setNotice('Keep at least one workspace. Create another before deleting this one.');return}if(window.confirm(`Delete workspace “${space.name}”? Its local workspace metadata will be removed.`))commit(items.filter(item=>item.id!==space.id),`${space.name} deleted.`)}
 function save(event:React.FormEvent<HTMLFormElement>){event.preventDefault();if(!editing)return;const data=new FormData(event.currentTarget);const name=String(data.get('name')??'').trim();if(!name){setNotice('Workspace name is required.');return}const updated={...editing,name,owner:String(data.get('owner')??'').trim(),startDate:String(data.get('startDate')??''),description:String(data.get('description')??'').trim()};commit(items.map(item=>item.id===updated.id?updated:item),`${name} updated.`);setEditing(null)}
 return <div className="global-workspace-picker"><button className="global-workspace-trigger" type="button" onClick={()=>setOpen(value=>!value)} aria-expanded={open}>{current.image?<img src={current.image} alt=""/>:<span>{current.name[0]??'P'}</span>}<div><small>PTCL WORKSPACE</small><strong>{current.name}</strong></div><ChevronDown size={15}/></button>{open&&<div className="global-workspace-menu"><label className="search"><Search size={15}/><input autoFocus value={search} onChange={event=>setSearch(event.target.value)} placeholder="Search workspaces…"/></label><div className="global-workspace-list">{matches.map(space=><article key={space.id} className={space.id===active?'active':''}><button type="button" className="workspace-select" onClick={()=>choose(space.id)}>{space.image?<img src={space.image} alt=""/>:<span>{space.name[0]}</span>}<div><strong>{space.name}</strong><small>{space.owner??space.description}</small></div></button><div className="workspace-list-actions"><button type="button" title="Edit workspace" aria-label={`Edit ${space.name}`} onClick={()=>setEditing(space)}><Pencil size={14}/></button><button type="button" title="Delete workspace" aria-label={`Delete ${space.name}`} onClick={()=>remove(space)}><Trash2 size={14}/></button></div></article>)}{!matches.length&&<p>No workspace found.</p>}</div>{notice&&<p className="workspace-notice">{notice}</p>}<button type="button" className="global-workspace-new" onClick={()=>{setOpen(false);window.dispatchEvent(new Event('pf360-open-workspace-tools'))}}><Plus size={16}/>New workspace</button></div>}{editing&&<div className="workspace-edit-overlay" onClick={()=>setEditing(null)}><form className="workspace-edit-panel" onSubmit={save} onClick={event=>event.stopPropagation()}><div className="section-title"><div><span className="eyebrow">WORKSPACE SETTINGS</span><h2>Edit workspace</h2></div><button type="button" className="icon-button" onClick={()=>setEditing(null)}><X size={18}/></button></div><label>Workspace name<input name="name" required defaultValue={editing.name}/></label><label>Owner<input name="owner" defaultValue={editing.owner}/></label><label>Start date<input name="startDate" type="date" defaultValue={editing.startDate}/></label><label>Description<textarea name="description" rows={3} defaultValue={editing.description}/></label><div className="modal-actions"><button className="primary" type="submit">Update workspace</button><button className="text-button" type="button" onClick={()=>setEditing(null)}>Cancel</button></div></form></div>}</div>
}
