'use client';

import { useEffect, useRef, useState } from 'react';
import { Camera, ChevronDown, Pencil, Save, X } from 'lucide-react';
import { loadDepartments, type AuthUser } from '../lib/auth';

export function ProfileMenu({user, onUpdate}: {user: AuthUser; onUpdate: (changes: Pick<AuthUser, 'fullName' | 'designation' | 'department' | 'email' | 'mobile' | 'photo'>) => void}) {
  const [open, setOpen] = useState(false), [editing, setEditing] = useState(false), [photo, setPhoto] = useState(user.photo ?? ''), [error, setError] = useState('');
  const input = useRef<HTMLInputElement>(null); const departments = loadDepartments();
  useEffect(() => { const openEditor = () => setEditing(true); window.addEventListener('pf360-open-profile', openEditor); return () => window.removeEventListener('pf360-open-profile', openEditor); }, []);
  function choosePhoto(file?: File) { if (!file) return; if (!file.type.startsWith('image/') || file.size > 2 * 1024 * 1024) { setError('Choose an image up to 2 MB.'); return; } const reader = new FileReader(); reader.onload = () => setPhoto(typeof reader.result === 'string' ? reader.result : ''); reader.readAsDataURL(file); }
  function save(event: React.FormEvent<HTMLFormElement>) { event.preventDefault(); const form = new FormData(event.currentTarget); onUpdate({fullName: String(form.get('fullName')).trim(), designation: String(form.get('designation')).trim(), department: String(form.get('department')), email: String(form.get('email')).trim().toLowerCase(), mobile: String(form.get('mobile')).trim(), photo: photo || undefined}); setEditing(false); setOpen(false); }
  return <div className="profile-menu"><button className="profile-trigger" aria-expanded={open} onClick={() => setOpen(value => !value)}>{user.photo?<img className="header-photo" src={user.photo} alt=""/>:<span className="avatar">{user.fullName.split(' ').map(word=>word[0]).slice(0,2).join('')}</span>}<span className="profile">{user.fullName}<small>{user.designation}</small></span><ChevronDown size={15}/></button>{open&&<div className="profile-dropdown"><strong>{user.role}</strong><span>{user.email}</span><button onClick={() => { setEditing(true); setOpen(false); }}><Pencil size={15}/>Update profile</button></div>}{editing&&<div className="modal-overlay" onClick={() => setEditing(false)}><section className="modal profile-editor" role="dialog" aria-modal="true" aria-label="Update profile" onClick={event => event.stopPropagation()}><button className="modal-close icon-button" aria-label="Close profile editor" onClick={() => setEditing(false)}><X size={20}/></button><div className="eyebrow">YOUR ACCOUNT</div><h2>Update profile</h2><p>Keep your workspace identity and contact details current.</p>{error&&<div className="inline-error">{error}</div>}<form onSubmit={save}><div className="profile-photo-edit"><button type="button" className="photo-picker" onClick={() => input.current?.click()}>{photo?<img src={photo} alt="Profile preview"/>:<Camera size={22}/>}</button><div><strong>Profile picture</strong><small>JPG, PNG or WebP · 2 MB max</small>{photo&&<button type="button" className="text-button" onClick={() => setPhoto('')}>Remove photo</button>}</div><input ref={input} className="sr-only" type="file" accept="image/png,image/jpeg,image/webp" onChange={event => choosePhoto(event.target.files?.[0])}/></div><label>Full name<input name="fullName" required maxLength={100} defaultValue={user.fullName}/></label><label>Designation<input name="designation" required maxLength={100} defaultValue={user.designation}/></label><label>Department<select name="department" defaultValue={user.department}>{departments.map(department => <option key={department}>{department}</option>)}</select></label><label>Email<input name="email" type="email" required defaultValue={user.email}/></label><label>Mobile number<input name="mobile" required maxLength={30} defaultValue={user.mobile}/></label><button className="primary" type="submit"><Save size={17}/>Save profile changes</button></form></section></div>}</div>;
}
